#!/usr/bin/env bash
set -euo pipefail

# Run the BYoVA adapter against a Nemotron voice-agent.
# Override any of these before running if your host/ports differ.

export NEMOTRON_VOICE_AGENT_WS="${NEMOTRON_VOICE_AGENT_WS:-${NEMOTRON_WS_BASE:-wss://127.0.0.1:7860}}"
export NEMOTRON_INSECURE_TLS="${NEMOTRON_INSECURE_TLS:-true}"

export NEMOTRON_BYOVA_ADAPTER_GRPC_HOST="${NEMOTRON_BYOVA_ADAPTER_GRPC_HOST:-0.0.0.0}"
export NEMOTRON_BYOVA_ADAPTER_GRPC_PORT="${NEMOTRON_BYOVA_ADAPTER_GRPC_PORT:-50061}"
export NEMOTRON_BYOVA_ADAPTER_HEALTH_HOST="${NEMOTRON_BYOVA_ADAPTER_HEALTH_HOST:-0.0.0.0}"
export NEMOTRON_BYOVA_ADAPTER_HEALTH_PORT="${NEMOTRON_BYOVA_ADAPTER_HEALTH_PORT:-8081}"
export ALLOW_PLAINTEXT_ADAPTER="${ALLOW_PLAINTEXT_ADAPTER:-false}"

# TLS for the adapter's public ports. Webex BYoVA requires TLS on the gRPC
# data-source URL. Plaintext is only allowed when explicitly enabled for
# local smoke testing.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ADAPTER_ROOT="$( cd "${SCRIPT_DIR}/.." && pwd )"
DEFAULT_TLS_CERT="${ADAPTER_ROOT}/certs/le/adapter.crt"
DEFAULT_TLS_KEY="${ADAPTER_ROOT}/certs/le/adapter.key"
export NEMOTRON_BYOVA_ADAPTER_TLS_CERT="${NEMOTRON_BYOVA_ADAPTER_TLS_CERT:-${DEFAULT_TLS_CERT}}"
export NEMOTRON_BYOVA_ADAPTER_TLS_KEY="${NEMOTRON_BYOVA_ADAPTER_TLS_KEY:-${DEFAULT_TLS_KEY}}"
if [[ ! -f "${NEMOTRON_BYOVA_ADAPTER_TLS_CERT}" || ! -f "${NEMOTRON_BYOVA_ADAPTER_TLS_KEY}" ]]; then
  if [[ "${ALLOW_PLAINTEXT_ADAPTER}" == "true" ]]; then
    echo "WARN: TLS cert/key not found; running plaintext for local testing only."
    unset NEMOTRON_BYOVA_ADAPTER_TLS_CERT NEMOTRON_BYOVA_ADAPTER_TLS_KEY
  else
    echo "ERROR: Webex BYOVA requires gRPC+TLS."
    echo "Set NEMOTRON_BYOVA_ADAPTER_TLS_CERT=/path/to/fullchain.pem"
    echo "Set NEMOTRON_BYOVA_ADAPTER_TLS_KEY=/path/to/privkey.pem"
    echo "For local-only smoke tests, set ALLOW_PLAINTEXT_ADAPTER=true."
    exit 1
  fi
fi

export ENABLE_CISCO_JWS_VALIDATION="${ENABLE_CISCO_JWS_VALIDATION:-false}"
export FIRST_AUDIO_TIMEOUT_SECS="${FIRST_AUDIO_TIMEOUT_SECS:-120}"
export ADAPTER_IDLE_SESSION_TIMEOUT_SECS="${ADAPTER_IDLE_SESSION_TIMEOUT_SECS:-120}"

echo "Starting cisco-webex-byova-adapter with:"
echo "  NEMOTRON_VOICE_AGENT_WS=${NEMOTRON_VOICE_AGENT_WS}"
echo "  NEMOTRON_BYOVA_ADAPTER_GRPC_HOST=${NEMOTRON_BYOVA_ADAPTER_GRPC_HOST}"
echo "  NEMOTRON_BYOVA_ADAPTER_GRPC_PORT=${NEMOTRON_BYOVA_ADAPTER_GRPC_PORT}"
echo "  NEMOTRON_BYOVA_ADAPTER_HEALTH_HOST=${NEMOTRON_BYOVA_ADAPTER_HEALTH_HOST}"
echo "  NEMOTRON_BYOVA_ADAPTER_HEALTH_PORT=${NEMOTRON_BYOVA_ADAPTER_HEALTH_PORT}"
echo "  NEMOTRON_BYOVA_ADAPTER_TLS_CERT=${NEMOTRON_BYOVA_ADAPTER_TLS_CERT:-<none>}"
echo "  NEMOTRON_BYOVA_ADAPTER_TLS_KEY=${NEMOTRON_BYOVA_ADAPTER_TLS_KEY:+<set>}"
echo "  ALLOW_PLAINTEXT_ADAPTER=${ALLOW_PLAINTEXT_ADAPTER}"
echo "  ENABLE_CISCO_JWS_VALIDATION=${ENABLE_CISCO_JWS_VALIDATION}"
echo "  FIRST_AUDIO_TIMEOUT_SECS=${FIRST_AUDIO_TIMEOUT_SECS}"
echo "  ADAPTER_IDLE_SESSION_TIMEOUT_SECS=${ADAPTER_IDLE_SESSION_TIMEOUT_SECS}"

(
  cd "${ADAPTER_ROOT}" || {
    echo "ERROR: failed to change directory to ${ADAPTER_ROOT}"
    exit 1
  }
  uv run cisco-webex-byova-adapter
)
