# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-2-Clause

"""Framework-independent VoiceClaw domain types."""

from voiceclaw.domain.capabilities import PendingToolQuery, SemanticTool, ToolProjectionState, ToolWork
from voiceclaw.domain.models import (
    AgentQueryChanged,
    AgentQueryKind,
    AgentQueryProjection,
    AgentQueryState,
    BackendCapabilities,
    BackendEvent,
    BackendEventKind,
    BackendOperation,
    CapabilityEvidence,
    CapabilitySource,
    CommandRecord,
    CommandState,
    DisplayPayload,
    DisplayState,
    Durability,
    EventDelivery,
    FrontendActivity,
    InputActivity,
    ModelActivity,
    OutputActivity,
    PresentationPriority,
    PresentationRecord,
    ResultAvailable,
    ResultState,
    SessionBinding,
    SessionControlSnapshot,
    SpeechRoute,
    SpeechState,
    WorkProjection,
    WorkResult,
    WorkState,
    WorkStateChanged,
)
from voiceclaw.domain.response_only import (
    REALTIME_PROJECTION_SCHEMA,
    RESULT_ENVELOPE_SCHEMA,
    RUNTIME_PROJECTION_SCHEMA,
    ResponseOnlyRequestState,
    ResponseOnlyResultEnvelope,
    ResponseOnlyResultEventKind,
    ResponseOnlyResultState,
    ResponseOnlySpeechSource,
    ResponseOnlyTerminalOutcome,
    ResponseOnlyUpdateKind,
)

__all__ = [
    "AgentQueryChanged",
    "AgentQueryKind",
    "AgentQueryProjection",
    "AgentQueryState",
    "BackendCapabilities",
    "BackendEvent",
    "BackendEventKind",
    "BackendOperation",
    "CapabilityEvidence",
    "CapabilitySource",
    "CommandRecord",
    "CommandState",
    "DisplayPayload",
    "DisplayState",
    "Durability",
    "EventDelivery",
    "FrontendActivity",
    "InputActivity",
    "ModelActivity",
    "OutputActivity",
    "PendingToolQuery",
    "PresentationPriority",
    "PresentationRecord",
    "REALTIME_PROJECTION_SCHEMA",
    "RESULT_ENVELOPE_SCHEMA",
    "RUNTIME_PROJECTION_SCHEMA",
    "ResultAvailable",
    "ResultState",
    "ResponseOnlyRequestState",
    "ResponseOnlyResultEventKind",
    "ResponseOnlyResultEnvelope",
    "ResponseOnlyResultState",
    "ResponseOnlySpeechSource",
    "ResponseOnlyTerminalOutcome",
    "ResponseOnlyUpdateKind",
    "SessionControlSnapshot",
    "SessionBinding",
    "SpeechRoute",
    "SpeechState",
    "SemanticTool",
    "ToolProjectionState",
    "ToolWork",
    "WorkProjection",
    "WorkResult",
    "WorkState",
    "WorkStateChanged",
]
